# Generated by Django 4.0.1 on 2022-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdaymsgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
