# Generated by Django 4.0.1 on 2022-02-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdaymsgs', '0002_message_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
